# Copyright (c) 2021. Quirino Gervacio
# MIT License. All Rights Reserved

version: "3"

services:
  crypto-botgo:
    image: qgervacio/crypto-botgo:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      --specFile /tmp/spec.yaml
      --logLevel debug
    volumes:
      - ./test:/tmp
